version: 0.2

phases:
  install:
    commands:
      - cd $HOME
      - echo "\nSetup .m2\n"
      - wget https://s3.amazonaws.com/vetd-build-assets/vetd-app-m2.tar.gz
      - tar -xvf vetd-app-m2.tar.gz
      - echo "\nUpgrade AWS CLI to the latest version; Install Leiningen; Install Clojure CLI tools\n"
      - wget https://raw.github.com/technomancy/leiningen/stable/bin/lein; chmod +x lein; mv lein /bin;
      - LEIN_ROOT=true lein
      - mkdir clj_tools_install; cd clj_tools_install
      - curl -O https://download.clojure.org/install/linux-install-1.10.0.411.sh; chmod +x linux-install-1.10.0.411.sh; ./linux-install-1.10.0.411.sh
      - cd $CODEBUILD_SRC_DIR
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  pre_build:
    commands:
      - echo "\nContents of the base directory:\n"
      - ls -al
      - echo
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - echo '{:vetd-env "BUILD"}' > .lein-env
      - LEIN_ROOT=true lein uberjar
      - mv ./target/uberjar/vetd-app.jar ./deploy
      - docker build -t vetd/vetd-app:latest ./deploy
      - docker tag vetd/vetd-app 744151627940.dkr.ecr.us-east-1.amazonaws.com/vetd-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 744151627940.dkr.ecr.us-east-1.amazonaws.com/vetd-app:latest
artifacts:
  files:
    - taskdef.json
    - appspec.yml
